### ISSUE TITLE
IndentationErrors and an undefined name

### ISSUE THREAD

**Issue by cclauss** [watson-developer-cloud/python-primer-companion-code#5]
[flake8](http://flake8.pycqa.org) testing of https://github.com/watson-developer-cloud/python-primer-companion-code on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./episode-2/django/src/projwatson/watsonlanguage/views/wl.py:105:4: E999 IndentationError: unexpected indent
    theTranslation = None
   ^
./episode-2/flask/src/translation.py:52:4: E999 IndentationError: unexpected indent
    theTranslation = None
   ^
./episode-6/django/src/projwatson/watsonlanguage/views/wl.py:103:9: F821 undefined name 'NaturalLanguageUnderstandingUtils'
  nlu = NaturalLanguageUnderstandingUtils()
        ^
2     E999 IndentationError: unexpected indent
1     F821 undefined name 'NaturalLanguageUnderstandingUtils'
3
```

**Comment by germanattanasio** [comment]
Hi @cclauss I don't think this repository is being maintained 😭

**Comment by chughts** [comment]
It is being maintained, but its the lowest priority of 4 weekend / out of hours jobs. I would prefer a pull request with the changes. That said all the samples need updating to make use of IAM keys.
